aspect_ratio = [16.0, 9.0] # [width, height]
image_width = 400 # image_height is determined dynamically by the width and aspect ratio
viewport_height = 2.0 # similarly, viewport width is determined dynamically from the aspect ratio
focal_length = 1.0 # distance between the camera and the viewport
samples_per_pixel = 100 # number of rays used to determine the color value for a pixel
max_ray_bounces = 100  # maximum number of reflections for any ray
vertical_field_of_view = 90
# TODO: need to add camera center here
